version: "3.7"
services:
 php:
  image: php:7.2-apache
  volumes:
   - ./src:/var/www/html
  restart: always
  container_name: php-container
  ports: 
   - "80:80"
  networks:
   - interno
 db:
  image: mysql
  volumes:
   - ./db:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: hugo
  networks:
   - interno
networks:
 interno:
  driver: "bridge"