version: "3.7"
services:
 php:
  build:
   context: .
  volumes:
   - ./first_php_symfhony:/var/www/html
   - ./conf/vhost.conf:/etc/apache2/sites-available/000-default.conf
  restart: always
  environment:
   - APACHE_ROOT=/var/www/html/start/public
  container_name: symfony-container2
  ports: 
   - "80:80"
  networks:
   - interno 
 db:
  image: mysql
  volumes:
   - ./db:/var/lib/mysql
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: hugo
  container_name : mysql
 
  networks:
   - interno
networks:
 interno:
  driver: "bridge"