version: "3.7"
services:
 db:
  image: mysql
  container_name: mysql-container
  command: --defalt-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: programadorabordo
  volumes:
   - ./docker-introducao/api/db/data:/var/lib/mysql
  restart: always
 api:
  build: "./docker-introducao/api"
  container_name: node-container
  restart: always
  volumes:
   - ./docker-introducao/api:/home/node/app
  ports: 
   - "9001:9001"
  depends_on:
   - db
 web:
  image: "php:7.2-apache"
  container_name: php-container
  restart: always
  volumes:
   - ./docker-introducao/website:/var/www/html
  ports:
   - "8888:80"
  depends_on:
   - api
